// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/v1/board.proto

package boardpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBoardRequest) Reset() {
	*x = CreateBoardRequest{}
	mi := &file_api_proto_v1_board_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoardRequest) ProtoMessage() {}

func (x *CreateBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoardRequest.ProtoReflect.Descriptor instead.
func (*CreateBoardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBoardRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBoardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBoardRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type CreateBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         *Board                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBoardResponse) Reset() {
	*x = CreateBoardResponse{}
	mi := &file_api_proto_v1_board_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoardResponse) ProtoMessage() {}

func (x *CreateBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoardResponse.ProtoReflect.Descriptor instead.
func (*CreateBoardResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBoardResponse) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

type GetBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardRequest) Reset() {
	*x = GetBoardRequest{}
	mi := &file_api_proto_v1_board_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardRequest) ProtoMessage() {}

func (x *GetBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardRequest.ProtoReflect.Descriptor instead.
func (*GetBoardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{2}
}

func (x *GetBoardRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *GetBoardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         *Board                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	Columns       []*Column              `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	Members       []*BoardMember         `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardResponse) Reset() {
	*x = GetBoardResponse{}
	mi := &file_api_proto_v1_board_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardResponse) ProtoMessage() {}

func (x *GetBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardResponse.ProtoReflect.Descriptor instead.
func (*GetBoardResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{3}
}

func (x *GetBoardResponse) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *GetBoardResponse) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *GetBoardResponse) GetMembers() []*BoardMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type ListBoardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	OwnerOnly     bool                   `protobuf:"varint,4,opt,name=owner_only,json=ownerOnly,proto3" json:"owner_only,omitempty"`
	Search        string                 `protobuf:"bytes,5,opt,name=search,proto3" json:"search,omitempty"`               // partial title search (ILIKE)
	SortBy        string                 `protobuf:"bytes,6,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"` // "updated_at" (default), "created_at", "title"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBoardsRequest) Reset() {
	*x = ListBoardsRequest{}
	mi := &file_api_proto_v1_board_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBoardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBoardsRequest) ProtoMessage() {}

func (x *ListBoardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBoardsRequest.ProtoReflect.Descriptor instead.
func (*ListBoardsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{4}
}

func (x *ListBoardsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListBoardsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListBoardsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListBoardsRequest) GetOwnerOnly() bool {
	if x != nil {
		return x.OwnerOnly
	}
	return false
}

func (x *ListBoardsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListBoardsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

type ListBoardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boards        []*Board               `protobuf:"bytes,1,rep,name=boards,proto3" json:"boards,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // cursor для следующей страницы
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBoardsResponse) Reset() {
	*x = ListBoardsResponse{}
	mi := &file_api_proto_v1_board_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBoardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBoardsResponse) ProtoMessage() {}

func (x *ListBoardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBoardsResponse.ProtoReflect.Descriptor instead.
func (*ListBoardsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{5}
}

func (x *ListBoardsResponse) GetBoards() []*Board {
	if x != nil {
		return x.Boards
	}
	return nil
}

func (x *ListBoardsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type UpdateBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBoardRequest) Reset() {
	*x = UpdateBoardRequest{}
	mi := &file_api_proto_v1_board_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBoardRequest) ProtoMessage() {}

func (x *UpdateBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBoardRequest.ProtoReflect.Descriptor instead.
func (*UpdateBoardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBoardRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *UpdateBoardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateBoardRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateBoardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateBoardRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UpdateBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         *Board                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBoardResponse) Reset() {
	*x = UpdateBoardResponse{}
	mi := &file_api_proto_v1_board_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBoardResponse) ProtoMessage() {}

func (x *UpdateBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBoardResponse.ProtoReflect.Descriptor instead.
func (*UpdateBoardResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateBoardResponse) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

type DeleteBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardIds      []string               `protobuf:"bytes,1,rep,name=board_ids,json=boardIds,proto3" json:"board_ids,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBoardRequest) Reset() {
	*x = DeleteBoardRequest{}
	mi := &file_api_proto_v1_board_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBoardRequest) ProtoMessage() {}

func (x *DeleteBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBoardRequest.ProtoReflect.Descriptor instead.
func (*DeleteBoardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteBoardRequest) GetBoardIds() []string {
	if x != nil {
		return x.BoardIds
	}
	return nil
}

func (x *DeleteBoardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AddColumnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Position      int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddColumnRequest) Reset() {
	*x = AddColumnRequest{}
	mi := &file_api_proto_v1_board_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddColumnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddColumnRequest) ProtoMessage() {}

func (x *AddColumnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddColumnRequest.ProtoReflect.Descriptor instead.
func (*AddColumnRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{9}
}

func (x *AddColumnRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *AddColumnRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddColumnRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddColumnRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type AddColumnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Column        *Column                `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddColumnResponse) Reset() {
	*x = AddColumnResponse{}
	mi := &file_api_proto_v1_board_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddColumnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddColumnResponse) ProtoMessage() {}

func (x *AddColumnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddColumnResponse.ProtoReflect.Descriptor instead.
func (*AddColumnResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{10}
}

func (x *AddColumnResponse) GetColumn() *Column {
	if x != nil {
		return x.Column
	}
	return nil
}

type GetColumnsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetColumnsRequest) Reset() {
	*x = GetColumnsRequest{}
	mi := &file_api_proto_v1_board_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetColumnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetColumnsRequest) ProtoMessage() {}

func (x *GetColumnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetColumnsRequest.ProtoReflect.Descriptor instead.
func (*GetColumnsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{11}
}

func (x *GetColumnsRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *GetColumnsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetColumnsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []*Column              `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetColumnsResponse) Reset() {
	*x = GetColumnsResponse{}
	mi := &file_api_proto_v1_board_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetColumnsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetColumnsResponse) ProtoMessage() {}

func (x *GetColumnsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetColumnsResponse.ProtoReflect.Descriptor instead.
func (*GetColumnsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{12}
}

func (x *GetColumnsResponse) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

type UpdateColumnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColumnId      string                 `protobuf:"bytes,1,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	BoardId       string                 `protobuf:"bytes,2,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateColumnRequest) Reset() {
	*x = UpdateColumnRequest{}
	mi := &file_api_proto_v1_board_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateColumnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateColumnRequest) ProtoMessage() {}

func (x *UpdateColumnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateColumnRequest.ProtoReflect.Descriptor instead.
func (*UpdateColumnRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateColumnRequest) GetColumnId() string {
	if x != nil {
		return x.ColumnId
	}
	return ""
}

func (x *UpdateColumnRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *UpdateColumnRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateColumnRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateColumnRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UpdateColumnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Column        *Column                `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateColumnResponse) Reset() {
	*x = UpdateColumnResponse{}
	mi := &file_api_proto_v1_board_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateColumnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateColumnResponse) ProtoMessage() {}

func (x *UpdateColumnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateColumnResponse.ProtoReflect.Descriptor instead.
func (*UpdateColumnResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateColumnResponse) GetColumn() *Column {
	if x != nil {
		return x.Column
	}
	return nil
}

type DeleteColumnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColumnId      string                 `protobuf:"bytes,1,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	BoardId       string                 `protobuf:"bytes,2,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteColumnRequest) Reset() {
	*x = DeleteColumnRequest{}
	mi := &file_api_proto_v1_board_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteColumnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteColumnRequest) ProtoMessage() {}

func (x *DeleteColumnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteColumnRequest.ProtoReflect.Descriptor instead.
func (*DeleteColumnRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteColumnRequest) GetColumnId() string {
	if x != nil {
		return x.ColumnId
	}
	return ""
}

func (x *DeleteColumnRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *DeleteColumnRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ReorderColumnsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Positions     []*ColumnPosition      `protobuf:"bytes,3,rep,name=positions,proto3" json:"positions,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderColumnsRequest) Reset() {
	*x = ReorderColumnsRequest{}
	mi := &file_api_proto_v1_board_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderColumnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderColumnsRequest) ProtoMessage() {}

func (x *ReorderColumnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderColumnsRequest.ProtoReflect.Descriptor instead.
func (*ReorderColumnsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{16}
}

func (x *ReorderColumnsRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *ReorderColumnsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReorderColumnsRequest) GetPositions() []*ColumnPosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *ReorderColumnsRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ColumnPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColumnId      string                 `protobuf:"bytes,1,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	Position      int32                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnPosition) Reset() {
	*x = ColumnPosition{}
	mi := &file_api_proto_v1_board_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnPosition) ProtoMessage() {}

func (x *ColumnPosition) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnPosition.ProtoReflect.Descriptor instead.
func (*ColumnPosition) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{17}
}

func (x *ColumnPosition) GetColumnId() string {
	if x != nil {
		return x.ColumnId
	}
	return ""
}

func (x *ColumnPosition) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type ReorderColumnsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []*Column              `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderColumnsResponse) Reset() {
	*x = ReorderColumnsResponse{}
	mi := &file_api_proto_v1_board_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderColumnsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderColumnsResponse) ProtoMessage() {}

func (x *ReorderColumnsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderColumnsResponse.ProtoReflect.Descriptor instead.
func (*ReorderColumnsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{18}
}

func (x *ReorderColumnsResponse) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

type CreateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColumnId      string                 `protobuf:"bytes,1,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	BoardId       string                 `protobuf:"bytes,2,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Position      string                 `protobuf:"bytes,6,opt,name=position,proto3" json:"position,omitempty"` // lexorank position (string, не int!)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardRequest) Reset() {
	*x = CreateCardRequest{}
	mi := &file_api_proto_v1_board_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardRequest) ProtoMessage() {}

func (x *CreateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardRequest.ProtoReflect.Descriptor instead.
func (*CreateCardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{19}
}

func (x *CreateCardRequest) GetColumnId() string {
	if x != nil {
		return x.ColumnId
	}
	return ""
}

func (x *CreateCardRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *CreateCardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCardRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCardRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

type CreateCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardResponse) Reset() {
	*x = CreateCardResponse{}
	mi := &file_api_proto_v1_board_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardResponse) ProtoMessage() {}

func (x *CreateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardResponse.ProtoReflect.Descriptor instead.
func (*CreateCardResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{20}
}

func (x *CreateCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type GetCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	BoardId       string                 `protobuf:"bytes,2,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardRequest) Reset() {
	*x = GetCardRequest{}
	mi := &file_api_proto_v1_board_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardRequest) ProtoMessage() {}

func (x *GetCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardRequest.ProtoReflect.Descriptor instead.
func (*GetCardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{21}
}

func (x *GetCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *GetCardRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *GetCardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardResponse) Reset() {
	*x = GetCardResponse{}
	mi := &file_api_proto_v1_board_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardResponse) ProtoMessage() {}

func (x *GetCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardResponse.ProtoReflect.Descriptor instead.
func (*GetCardResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{22}
}

func (x *GetCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type GetCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColumnId      string                 `protobuf:"bytes,1,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	BoardId       string                 `protobuf:"bytes,2,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsRequest) Reset() {
	*x = GetCardsRequest{}
	mi := &file_api_proto_v1_board_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsRequest) ProtoMessage() {}

func (x *GetCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsRequest.ProtoReflect.Descriptor instead.
func (*GetCardsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{23}
}

func (x *GetCardsRequest) GetColumnId() string {
	if x != nil {
		return x.ColumnId
	}
	return ""
}

func (x *GetCardsRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *GetCardsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsResponse) Reset() {
	*x = GetCardsResponse{}
	mi := &file_api_proto_v1_board_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsResponse) ProtoMessage() {}

func (x *GetCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsResponse.ProtoReflect.Descriptor instead.
func (*GetCardsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{24}
}

func (x *GetCardsResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type UpdateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	BoardId       string                 `protobuf:"bytes,2,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	AssigneeId    string                 `protobuf:"bytes,6,opt,name=assignee_id,json=assigneeId,proto3" json:"assignee_id,omitempty"`
	Version       int32                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardRequest) Reset() {
	*x = UpdateCardRequest{}
	mi := &file_api_proto_v1_board_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardRequest) ProtoMessage() {}

func (x *UpdateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateCardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *UpdateCardRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *UpdateCardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateCardRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateCardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCardRequest) GetAssigneeId() string {
	if x != nil {
		return x.AssigneeId
	}
	return ""
}

func (x *UpdateCardRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UpdateCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardResponse) Reset() {
	*x = UpdateCardResponse{}
	mi := &file_api_proto_v1_board_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardResponse) ProtoMessage() {}

func (x *UpdateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardResponse.ProtoReflect.Descriptor instead.
func (*UpdateCardResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type MoveCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	BoardId       string                 `protobuf:"bytes,2,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	FromColumnId  string                 `protobuf:"bytes,3,opt,name=from_column_id,json=fromColumnId,proto3" json:"from_column_id,omitempty"`
	ToColumnId    string                 `protobuf:"bytes,4,opt,name=to_column_id,json=toColumnId,proto3" json:"to_column_id,omitempty"`
	Position      string                 `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"` // lexorank position (string, не int!)
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Version       int32                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveCardRequest) Reset() {
	*x = MoveCardRequest{}
	mi := &file_api_proto_v1_board_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveCardRequest) ProtoMessage() {}

func (x *MoveCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveCardRequest.ProtoReflect.Descriptor instead.
func (*MoveCardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{27}
}

func (x *MoveCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *MoveCardRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *MoveCardRequest) GetFromColumnId() string {
	if x != nil {
		return x.FromColumnId
	}
	return ""
}

func (x *MoveCardRequest) GetToColumnId() string {
	if x != nil {
		return x.ToColumnId
	}
	return ""
}

func (x *MoveCardRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *MoveCardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MoveCardRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type MoveCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	CardsInColumn []*Card                `protobuf:"bytes,2,rep,name=cards_in_column,json=cardsInColumn,proto3" json:"cards_in_column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveCardResponse) Reset() {
	*x = MoveCardResponse{}
	mi := &file_api_proto_v1_board_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveCardResponse) ProtoMessage() {}

func (x *MoveCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveCardResponse.ProtoReflect.Descriptor instead.
func (*MoveCardResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{28}
}

func (x *MoveCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *MoveCardResponse) GetCardsInColumn() []*Card {
	if x != nil {
		return x.CardsInColumn
	}
	return nil
}

type DeleteCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardIds       []string               `protobuf:"bytes,1,rep,name=card_ids,json=cardIds,proto3" json:"card_ids,omitempty"`
	BoardId       string                 `protobuf:"bytes,2,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardRequest) Reset() {
	*x = DeleteCardRequest{}
	mi := &file_api_proto_v1_board_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardRequest) ProtoMessage() {}

func (x *DeleteCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteCardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteCardRequest) GetCardIds() []string {
	if x != nil {
		return x.CardIds
	}
	return nil
}

func (x *DeleteCardRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *DeleteCardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AddMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MemberUserId  string                 `protobuf:"bytes,3,opt,name=member_user_id,json=memberUserId,proto3" json:"member_user_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_api_proto_v1_board_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{30}
}

func (x *AddMemberRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *AddMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddMemberRequest) GetMemberUserId() string {
	if x != nil {
		return x.MemberUserId
	}
	return ""
}

func (x *AddMemberRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type AddMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *BoardMember           `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberResponse) Reset() {
	*x = AddMemberResponse{}
	mi := &file_api_proto_v1_board_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberResponse) ProtoMessage() {}

func (x *AddMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberResponse.ProtoReflect.Descriptor instead.
func (*AddMemberResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{31}
}

func (x *AddMemberResponse) GetMember() *BoardMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MemberUserId  string                 `protobuf:"bytes,3,opt,name=member_user_id,json=memberUserId,proto3" json:"member_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_api_proto_v1_board_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{32}
}

func (x *RemoveMemberRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *RemoveMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveMemberRequest) GetMemberUserId() string {
	if x != nil {
		return x.MemberUserId
	}
	return ""
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_api_proto_v1_board_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{33}
}

func (x *ListMembersRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *ListMembersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*BoardMember         `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_api_proto_v1_board_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{34}
}

func (x *ListMembersResponse) GetMembers() []*BoardMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type Board struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OwnerId       string                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_api_proto_v1_board_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{35}
}

func (x *Board) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Board) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Board) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Board) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Board) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Board) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Board) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Column struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BoardId       string                 `protobuf:"bytes,2,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Position      int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_api_proto_v1_board_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{36}
}

func (x *Column) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Column) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *Column) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Column) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Column) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Column) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Column) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ColumnId      string                 `protobuf:"bytes,2,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	BoardId       string                 `protobuf:"bytes,3,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Position      string                 `protobuf:"bytes,6,opt,name=position,proto3" json:"position,omitempty"` // lexorank position (string: "a", "am", "b", ...)
	AssigneeId    string                 `protobuf:"bytes,7,opt,name=assignee_id,json=assigneeId,proto3" json:"assignee_id,omitempty"`
	Version       int32                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatorId     string                 `protobuf:"bytes,11,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_api_proto_v1_board_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{37}
}

func (x *Card) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card) GetColumnId() string {
	if x != nil {
		return x.ColumnId
	}
	return ""
}

func (x *Card) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *Card) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Card) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Card) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Card) GetAssigneeId() string {
	if x != nil {
		return x.AssigneeId
	}
	return ""
}

func (x *Card) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Card) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Card) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Card) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

type BoardMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardMember) Reset() {
	*x = BoardMember{}
	mi := &file_api_proto_v1_board_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardMember) ProtoMessage() {}

func (x *BoardMember) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_board_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardMember.ProtoReflect.Descriptor instead.
func (*BoardMember) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_board_proto_rawDescGZIP(), []int{38}
}

func (x *BoardMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BoardMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *BoardMember) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BoardMember) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

var File_api_proto_v1_board_proto protoreflect.FileDescriptor

const file_api_proto_v1_board_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/v1/board.proto\x12\bboard.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"g\n" +
	"\x12CreateBoardRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\"<\n" +
	"\x13CreateBoardResponse\x12%\n" +
	"\x05board\x18\x01 \x01(\v2\x0f.board.v1.BoardR\x05board\"E\n" +
	"\x0fGetBoardRequest\x12\x19\n" +
	"\bboard_id\x18\x01 \x01(\tR\aboardId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x96\x01\n" +
	"\x10GetBoardResponse\x12%\n" +
	"\x05board\x18\x01 \x01(\v2\x0f.board.v1.BoardR\x05board\x12*\n" +
	"\acolumns\x18\x02 \x03(\v2\x10.board.v1.ColumnR\acolumns\x12/\n" +
	"\amembers\x18\x03 \x03(\v2\x15.board.v1.BoardMemberR\amembers\"\xaa\x01\n" +
	"\x11ListBoardsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x12\x1d\n" +
	"\n" +
	"owner_only\x18\x04 \x01(\bR\townerOnly\x12\x16\n" +
	"\x06search\x18\x05 \x01(\tR\x06search\x12\x17\n" +
	"\asort_by\x18\x06 \x01(\tR\x06sortBy\"^\n" +
	"\x12ListBoardsResponse\x12'\n" +
	"\x06boards\x18\x01 \x03(\v2\x0f.board.v1.BoardR\x06boards\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\x9a\x01\n" +
	"\x12UpdateBoardRequest\x12\x19\n" +
	"\bboard_id\x18\x01 \x01(\tR\aboardId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\"<\n" +
	"\x13UpdateBoardResponse\x12%\n" +
	"\x05board\x18\x01 \x01(\v2\x0f.board.v1.BoardR\x05board\"J\n" +
	"\x12DeleteBoardRequest\x12\x1b\n" +
	"\tboard_ids\x18\x01 \x03(\tR\bboardIds\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"x\n" +
	"\x10AddColumnRequest\x12\x19\n" +
	"\bboard_id\x18\x01 \x01(\tR\aboardId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\"=\n" +
	"\x11AddColumnResponse\x12(\n" +
	"\x06column\x18\x01 \x01(\v2\x10.board.v1.ColumnR\x06column\"G\n" +
	"\x11GetColumnsRequest\x12\x19\n" +
	"\bboard_id\x18\x01 \x01(\tR\aboardId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"@\n" +
	"\x12GetColumnsResponse\x12*\n" +
	"\acolumns\x18\x01 \x03(\v2\x10.board.v1.ColumnR\acolumns\"\x96\x01\n" +
	"\x13UpdateColumnRequest\x12\x1b\n" +
	"\tcolumn_id\x18\x01 \x01(\tR\bcolumnId\x12\x19\n" +
	"\bboard_id\x18\x02 \x01(\tR\aboardId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\"@\n" +
	"\x14UpdateColumnResponse\x12(\n" +
	"\x06column\x18\x01 \x01(\v2\x10.board.v1.ColumnR\x06column\"f\n" +
	"\x13DeleteColumnRequest\x12\x1b\n" +
	"\tcolumn_id\x18\x01 \x01(\tR\bcolumnId\x12\x19\n" +
	"\bboard_id\x18\x02 \x01(\tR\aboardId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\x9d\x01\n" +
	"\x15ReorderColumnsRequest\x12\x19\n" +
	"\bboard_id\x18\x01 \x01(\tR\aboardId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x126\n" +
	"\tpositions\x18\x03 \x03(\v2\x18.board.v1.ColumnPositionR\tpositions\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\"I\n" +
	"\x0eColumnPosition\x12\x1b\n" +
	"\tcolumn_id\x18\x01 \x01(\tR\bcolumnId\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\"D\n" +
	"\x16ReorderColumnsResponse\x12*\n" +
	"\acolumns\x18\x01 \x03(\v2\x10.board.v1.ColumnR\acolumns\"\xb8\x01\n" +
	"\x11CreateCardRequest\x12\x1b\n" +
	"\tcolumn_id\x18\x01 \x01(\tR\bcolumnId\x12\x19\n" +
	"\bboard_id\x18\x02 \x01(\tR\aboardId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bposition\x18\x06 \x01(\tR\bposition\"8\n" +
	"\x12CreateCardResponse\x12\"\n" +
	"\x04card\x18\x01 \x01(\v2\x0e.board.v1.CardR\x04card\"]\n" +
	"\x0eGetCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x19\n" +
	"\bboard_id\x18\x02 \x01(\tR\aboardId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"5\n" +
	"\x0fGetCardResponse\x12\"\n" +
	"\x04card\x18\x01 \x01(\v2\x0e.board.v1.CardR\x04card\"b\n" +
	"\x0fGetCardsRequest\x12\x1b\n" +
	"\tcolumn_id\x18\x01 \x01(\tR\bcolumnId\x12\x19\n" +
	"\bboard_id\x18\x02 \x01(\tR\aboardId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"8\n" +
	"\x10GetCardsResponse\x12$\n" +
	"\x05cards\x18\x01 \x03(\v2\x0e.board.v1.CardR\x05cards\"\xd3\x01\n" +
	"\x11UpdateCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x19\n" +
	"\bboard_id\x18\x02 \x01(\tR\aboardId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1f\n" +
	"\vassignee_id\x18\x06 \x01(\tR\n" +
	"assigneeId\x12\x18\n" +
	"\aversion\x18\a \x01(\x05R\aversion\"8\n" +
	"\x12UpdateCardResponse\x12\"\n" +
	"\x04card\x18\x01 \x01(\v2\x0e.board.v1.CardR\x04card\"\xdc\x01\n" +
	"\x0fMoveCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x19\n" +
	"\bboard_id\x18\x02 \x01(\tR\aboardId\x12$\n" +
	"\x0efrom_column_id\x18\x03 \x01(\tR\ffromColumnId\x12 \n" +
	"\fto_column_id\x18\x04 \x01(\tR\n" +
	"toColumnId\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\tR\bposition\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x12\x18\n" +
	"\aversion\x18\a \x01(\x05R\aversion\"n\n" +
	"\x10MoveCardResponse\x12\"\n" +
	"\x04card\x18\x01 \x01(\v2\x0e.board.v1.CardR\x04card\x126\n" +
	"\x0fcards_in_column\x18\x02 \x03(\v2\x0e.board.v1.CardR\rcardsInColumn\"b\n" +
	"\x11DeleteCardRequest\x12\x19\n" +
	"\bcard_ids\x18\x01 \x03(\tR\acardIds\x12\x19\n" +
	"\bboard_id\x18\x02 \x01(\tR\aboardId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\x80\x01\n" +
	"\x10AddMemberRequest\x12\x19\n" +
	"\bboard_id\x18\x01 \x01(\tR\aboardId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12$\n" +
	"\x0emember_user_id\x18\x03 \x01(\tR\fmemberUserId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"B\n" +
	"\x11AddMemberResponse\x12-\n" +
	"\x06member\x18\x01 \x01(\v2\x15.board.v1.BoardMemberR\x06member\"o\n" +
	"\x13RemoveMemberRequest\x12\x19\n" +
	"\bboard_id\x18\x01 \x01(\tR\aboardId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12$\n" +
	"\x0emember_user_id\x18\x03 \x01(\tR\fmemberUserId\"H\n" +
	"\x12ListMembersRequest\x12\x19\n" +
	"\bboard_id\x18\x01 \x01(\tR\aboardId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"F\n" +
	"\x13ListMembersResponse\x12/\n" +
	"\amembers\x18\x01 \x03(\v2\x15.board.v1.BoardMemberR\amembers\"\xfa\x01\n" +
	"\x05Board\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf5\x01\n" +
	"\x06Column\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bboard_id\x18\x02 \x01(\tR\aboardId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf2\x02\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tcolumn_id\x18\x02 \x01(\tR\bcolumnId\x12\x19\n" +
	"\bboard_id\x18\x03 \x01(\tR\aboardId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bposition\x18\x06 \x01(\tR\bposition\x12\x1f\n" +
	"\vassignee_id\x18\a \x01(\tR\n" +
	"assigneeId\x12\x18\n" +
	"\aversion\x18\b \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"creator_id\x18\v \x01(\tR\tcreatorId\"\x8d\x01\n" +
	"\vBoardMember\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x127\n" +
	"\tjoined_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt2\xe5\n" +
	"\n" +
	"\fBoardService\x12J\n" +
	"\vCreateBoard\x12\x1c.board.v1.CreateBoardRequest\x1a\x1d.board.v1.CreateBoardResponse\x12A\n" +
	"\bGetBoard\x12\x19.board.v1.GetBoardRequest\x1a\x1a.board.v1.GetBoardResponse\x12G\n" +
	"\n" +
	"ListBoards\x12\x1b.board.v1.ListBoardsRequest\x1a\x1c.board.v1.ListBoardsResponse\x12J\n" +
	"\vUpdateBoard\x12\x1c.board.v1.UpdateBoardRequest\x1a\x1d.board.v1.UpdateBoardResponse\x12C\n" +
	"\vDeleteBoard\x12\x1c.board.v1.DeleteBoardRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\tAddColumn\x12\x1a.board.v1.AddColumnRequest\x1a\x1b.board.v1.AddColumnResponse\x12G\n" +
	"\n" +
	"GetColumns\x12\x1b.board.v1.GetColumnsRequest\x1a\x1c.board.v1.GetColumnsResponse\x12M\n" +
	"\fUpdateColumn\x12\x1d.board.v1.UpdateColumnRequest\x1a\x1e.board.v1.UpdateColumnResponse\x12E\n" +
	"\fDeleteColumn\x12\x1d.board.v1.DeleteColumnRequest\x1a\x16.google.protobuf.Empty\x12S\n" +
	"\x0eReorderColumns\x12\x1f.board.v1.ReorderColumnsRequest\x1a .board.v1.ReorderColumnsResponse\x12G\n" +
	"\n" +
	"CreateCard\x12\x1b.board.v1.CreateCardRequest\x1a\x1c.board.v1.CreateCardResponse\x12>\n" +
	"\aGetCard\x12\x18.board.v1.GetCardRequest\x1a\x19.board.v1.GetCardResponse\x12A\n" +
	"\bGetCards\x12\x19.board.v1.GetCardsRequest\x1a\x1a.board.v1.GetCardsResponse\x12G\n" +
	"\n" +
	"UpdateCard\x12\x1b.board.v1.UpdateCardRequest\x1a\x1c.board.v1.UpdateCardResponse\x12A\n" +
	"\bMoveCard\x12\x19.board.v1.MoveCardRequest\x1a\x1a.board.v1.MoveCardResponse\x12A\n" +
	"\n" +
	"DeleteCard\x12\x1b.board.v1.DeleteCardRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\tAddMember\x12\x1a.board.v1.AddMemberRequest\x1a\x1b.board.v1.AddMemberResponse\x12E\n" +
	"\fRemoveMember\x12\x1d.board.v1.RemoveMemberRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\vListMembers\x12\x1c.board.v1.ListMembersRequest\x1a\x1d.board.v1.ListMembersResponseB@Z>github.com/RomaLytar/yammi/services/board/api/proto/v1;boardpbb\x06proto3"

var (
	file_api_proto_v1_board_proto_rawDescOnce sync.Once
	file_api_proto_v1_board_proto_rawDescData []byte
)

func file_api_proto_v1_board_proto_rawDescGZIP() []byte {
	file_api_proto_v1_board_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_board_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_board_proto_rawDesc), len(file_api_proto_v1_board_proto_rawDesc)))
	})
	return file_api_proto_v1_board_proto_rawDescData
}

var file_api_proto_v1_board_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_api_proto_v1_board_proto_goTypes = []any{
	(*CreateBoardRequest)(nil),     // 0: board.v1.CreateBoardRequest
	(*CreateBoardResponse)(nil),    // 1: board.v1.CreateBoardResponse
	(*GetBoardRequest)(nil),        // 2: board.v1.GetBoardRequest
	(*GetBoardResponse)(nil),       // 3: board.v1.GetBoardResponse
	(*ListBoardsRequest)(nil),      // 4: board.v1.ListBoardsRequest
	(*ListBoardsResponse)(nil),     // 5: board.v1.ListBoardsResponse
	(*UpdateBoardRequest)(nil),     // 6: board.v1.UpdateBoardRequest
	(*UpdateBoardResponse)(nil),    // 7: board.v1.UpdateBoardResponse
	(*DeleteBoardRequest)(nil),     // 8: board.v1.DeleteBoardRequest
	(*AddColumnRequest)(nil),       // 9: board.v1.AddColumnRequest
	(*AddColumnResponse)(nil),      // 10: board.v1.AddColumnResponse
	(*GetColumnsRequest)(nil),      // 11: board.v1.GetColumnsRequest
	(*GetColumnsResponse)(nil),     // 12: board.v1.GetColumnsResponse
	(*UpdateColumnRequest)(nil),    // 13: board.v1.UpdateColumnRequest
	(*UpdateColumnResponse)(nil),   // 14: board.v1.UpdateColumnResponse
	(*DeleteColumnRequest)(nil),    // 15: board.v1.DeleteColumnRequest
	(*ReorderColumnsRequest)(nil),  // 16: board.v1.ReorderColumnsRequest
	(*ColumnPosition)(nil),         // 17: board.v1.ColumnPosition
	(*ReorderColumnsResponse)(nil), // 18: board.v1.ReorderColumnsResponse
	(*CreateCardRequest)(nil),      // 19: board.v1.CreateCardRequest
	(*CreateCardResponse)(nil),     // 20: board.v1.CreateCardResponse
	(*GetCardRequest)(nil),         // 21: board.v1.GetCardRequest
	(*GetCardResponse)(nil),        // 22: board.v1.GetCardResponse
	(*GetCardsRequest)(nil),        // 23: board.v1.GetCardsRequest
	(*GetCardsResponse)(nil),       // 24: board.v1.GetCardsResponse
	(*UpdateCardRequest)(nil),      // 25: board.v1.UpdateCardRequest
	(*UpdateCardResponse)(nil),     // 26: board.v1.UpdateCardResponse
	(*MoveCardRequest)(nil),        // 27: board.v1.MoveCardRequest
	(*MoveCardResponse)(nil),       // 28: board.v1.MoveCardResponse
	(*DeleteCardRequest)(nil),      // 29: board.v1.DeleteCardRequest
	(*AddMemberRequest)(nil),       // 30: board.v1.AddMemberRequest
	(*AddMemberResponse)(nil),      // 31: board.v1.AddMemberResponse
	(*RemoveMemberRequest)(nil),    // 32: board.v1.RemoveMemberRequest
	(*ListMembersRequest)(nil),     // 33: board.v1.ListMembersRequest
	(*ListMembersResponse)(nil),    // 34: board.v1.ListMembersResponse
	(*Board)(nil),                  // 35: board.v1.Board
	(*Column)(nil),                 // 36: board.v1.Column
	(*Card)(nil),                   // 37: board.v1.Card
	(*BoardMember)(nil),            // 38: board.v1.BoardMember
	(*timestamppb.Timestamp)(nil),  // 39: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 40: google.protobuf.Empty
}
var file_api_proto_v1_board_proto_depIdxs = []int32{
	35, // 0: board.v1.CreateBoardResponse.board:type_name -> board.v1.Board
	35, // 1: board.v1.GetBoardResponse.board:type_name -> board.v1.Board
	36, // 2: board.v1.GetBoardResponse.columns:type_name -> board.v1.Column
	38, // 3: board.v1.GetBoardResponse.members:type_name -> board.v1.BoardMember
	35, // 4: board.v1.ListBoardsResponse.boards:type_name -> board.v1.Board
	35, // 5: board.v1.UpdateBoardResponse.board:type_name -> board.v1.Board
	36, // 6: board.v1.AddColumnResponse.column:type_name -> board.v1.Column
	36, // 7: board.v1.GetColumnsResponse.columns:type_name -> board.v1.Column
	36, // 8: board.v1.UpdateColumnResponse.column:type_name -> board.v1.Column
	17, // 9: board.v1.ReorderColumnsRequest.positions:type_name -> board.v1.ColumnPosition
	36, // 10: board.v1.ReorderColumnsResponse.columns:type_name -> board.v1.Column
	37, // 11: board.v1.CreateCardResponse.card:type_name -> board.v1.Card
	37, // 12: board.v1.GetCardResponse.card:type_name -> board.v1.Card
	37, // 13: board.v1.GetCardsResponse.cards:type_name -> board.v1.Card
	37, // 14: board.v1.UpdateCardResponse.card:type_name -> board.v1.Card
	37, // 15: board.v1.MoveCardResponse.card:type_name -> board.v1.Card
	37, // 16: board.v1.MoveCardResponse.cards_in_column:type_name -> board.v1.Card
	38, // 17: board.v1.AddMemberResponse.member:type_name -> board.v1.BoardMember
	38, // 18: board.v1.ListMembersResponse.members:type_name -> board.v1.BoardMember
	39, // 19: board.v1.Board.created_at:type_name -> google.protobuf.Timestamp
	39, // 20: board.v1.Board.updated_at:type_name -> google.protobuf.Timestamp
	39, // 21: board.v1.Column.created_at:type_name -> google.protobuf.Timestamp
	39, // 22: board.v1.Column.updated_at:type_name -> google.protobuf.Timestamp
	39, // 23: board.v1.Card.created_at:type_name -> google.protobuf.Timestamp
	39, // 24: board.v1.Card.updated_at:type_name -> google.protobuf.Timestamp
	39, // 25: board.v1.BoardMember.joined_at:type_name -> google.protobuf.Timestamp
	0,  // 26: board.v1.BoardService.CreateBoard:input_type -> board.v1.CreateBoardRequest
	2,  // 27: board.v1.BoardService.GetBoard:input_type -> board.v1.GetBoardRequest
	4,  // 28: board.v1.BoardService.ListBoards:input_type -> board.v1.ListBoardsRequest
	6,  // 29: board.v1.BoardService.UpdateBoard:input_type -> board.v1.UpdateBoardRequest
	8,  // 30: board.v1.BoardService.DeleteBoard:input_type -> board.v1.DeleteBoardRequest
	9,  // 31: board.v1.BoardService.AddColumn:input_type -> board.v1.AddColumnRequest
	11, // 32: board.v1.BoardService.GetColumns:input_type -> board.v1.GetColumnsRequest
	13, // 33: board.v1.BoardService.UpdateColumn:input_type -> board.v1.UpdateColumnRequest
	15, // 34: board.v1.BoardService.DeleteColumn:input_type -> board.v1.DeleteColumnRequest
	16, // 35: board.v1.BoardService.ReorderColumns:input_type -> board.v1.ReorderColumnsRequest
	19, // 36: board.v1.BoardService.CreateCard:input_type -> board.v1.CreateCardRequest
	21, // 37: board.v1.BoardService.GetCard:input_type -> board.v1.GetCardRequest
	23, // 38: board.v1.BoardService.GetCards:input_type -> board.v1.GetCardsRequest
	25, // 39: board.v1.BoardService.UpdateCard:input_type -> board.v1.UpdateCardRequest
	27, // 40: board.v1.BoardService.MoveCard:input_type -> board.v1.MoveCardRequest
	29, // 41: board.v1.BoardService.DeleteCard:input_type -> board.v1.DeleteCardRequest
	30, // 42: board.v1.BoardService.AddMember:input_type -> board.v1.AddMemberRequest
	32, // 43: board.v1.BoardService.RemoveMember:input_type -> board.v1.RemoveMemberRequest
	33, // 44: board.v1.BoardService.ListMembers:input_type -> board.v1.ListMembersRequest
	1,  // 45: board.v1.BoardService.CreateBoard:output_type -> board.v1.CreateBoardResponse
	3,  // 46: board.v1.BoardService.GetBoard:output_type -> board.v1.GetBoardResponse
	5,  // 47: board.v1.BoardService.ListBoards:output_type -> board.v1.ListBoardsResponse
	7,  // 48: board.v1.BoardService.UpdateBoard:output_type -> board.v1.UpdateBoardResponse
	40, // 49: board.v1.BoardService.DeleteBoard:output_type -> google.protobuf.Empty
	10, // 50: board.v1.BoardService.AddColumn:output_type -> board.v1.AddColumnResponse
	12, // 51: board.v1.BoardService.GetColumns:output_type -> board.v1.GetColumnsResponse
	14, // 52: board.v1.BoardService.UpdateColumn:output_type -> board.v1.UpdateColumnResponse
	40, // 53: board.v1.BoardService.DeleteColumn:output_type -> google.protobuf.Empty
	18, // 54: board.v1.BoardService.ReorderColumns:output_type -> board.v1.ReorderColumnsResponse
	20, // 55: board.v1.BoardService.CreateCard:output_type -> board.v1.CreateCardResponse
	22, // 56: board.v1.BoardService.GetCard:output_type -> board.v1.GetCardResponse
	24, // 57: board.v1.BoardService.GetCards:output_type -> board.v1.GetCardsResponse
	26, // 58: board.v1.BoardService.UpdateCard:output_type -> board.v1.UpdateCardResponse
	28, // 59: board.v1.BoardService.MoveCard:output_type -> board.v1.MoveCardResponse
	40, // 60: board.v1.BoardService.DeleteCard:output_type -> google.protobuf.Empty
	31, // 61: board.v1.BoardService.AddMember:output_type -> board.v1.AddMemberResponse
	40, // 62: board.v1.BoardService.RemoveMember:output_type -> google.protobuf.Empty
	34, // 63: board.v1.BoardService.ListMembers:output_type -> board.v1.ListMembersResponse
	45, // [45:64] is the sub-list for method output_type
	26, // [26:45] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_api_proto_v1_board_proto_init() }
func file_api_proto_v1_board_proto_init() {
	if File_api_proto_v1_board_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_board_proto_rawDesc), len(file_api_proto_v1_board_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_board_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_board_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_board_proto_msgTypes,
	}.Build()
	File_api_proto_v1_board_proto = out.File
	file_api_proto_v1_board_proto_goTypes = nil
	file_api_proto_v1_board_proto_depIdxs = nil
}
